/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.PrimaCucumber;

//import org.junit.Test;
//import static org.junit.Assert.*;

public class PrimaTest {
    /*@Test public void testSomeLibraryMethod() {
        Prima classUnderTest = new Prima();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }*/
}
